FROM apache/airflow:2.8.0-python3.10

USER root

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copier et installer requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Initialiser la base de données Airflow
RUN airflow db init
